# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-ast
        name: python check ast
    -   id: trailing-whitespace
        name: trim trailing whitespace
        files: (.*\.py$|.*\.css$|.*\.js$|.*\.html$)
    -   id: end-of-file-fixer
        name: end of line fixer
        files: (.*\.py$|.*\.css$|.*\.js$|.*\.html$)
    -   id: check-merge-conflict
        name: check merge conflicts
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
    -   id: black
        additional_dependencies:
            - click<8.1.0
        files: (.*\.py$)
        exclude: ^(.*\/migrations\/.*\.py|.*\.cfg$)$
        language: python
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
      args:
          - "--max-line-length=88"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E266,E501,W503,F403,F401,E402"
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
        args:
          - --profile
          - black
